name: "Release"

on:
  release:
    types: [created]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm install --force

      # Get sub modules
      - name: Sub modules 1
        run: npm run fetch:submodules
      - name: Sub modules 2
        run: npm run fetch:submodules:update

      - name: build
        run: npm run build

      - name: clean up
        run: rm -r ./lib/cpg-api

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
